# Generated by Django 2.1.4 on 2018-12-13 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, unique=True)),
                ('texto', models.CharField(blank=True, max_length=2000)),
                ('responsavel', models.CharField(blank=True, max_length=300)),
                ('funcao', models.CharField(blank=True, max_length=300)),
                ('foto', models.BinaryField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('texto', models.CharField(blank=True, max_length=2000)),
                ('funcao', models.CharField(blank=True, max_length=300)),
                ('cargo', models.CharField(max_length=2000)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('foto', models.BinaryField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('texto', models.CharField(blank=True, max_length=2000)),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organograma.Orgao')),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organograma.Time'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organograma.Time'),
        ),
    ]
