# Generated by Django 2.1.4 on 2018-12-15 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, unique=True)),
                ('texto', models.CharField(blank=True, max_length=2000, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=300, null=True)),
                ('funcao', models.CharField(blank=True, max_length=300, null=True)),
                ('local', models.CharField(blank=True, max_length=300, null=True)),
                ('foto', models.BinaryField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('texto', models.CharField(blank=True, max_length=2000, null=True)),
                ('funcao', models.CharField(blank=True, max_length=300, null=True)),
                ('cargo', models.CharField(max_length=2000)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('foto', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('texto', models.CharField(blank=True, max_length=300, null=True)),
                ('andamento', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('release', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('natureza', models.CharField(blank=True, max_length=100, null=True)),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('texto', models.CharField(blank=True, max_length=2000, null=True)),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organograma.Orgao')),
                ('projeto_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organograma.Projeto')),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='projetos',
            field=models.ManyToManyField(to='organograma.Projeto'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organograma.Time'),
        ),
    ]
