# Generated by Django 2.1.4 on 2018-12-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organograma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgao',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
