# Generated by Django 2.1.4 on 2018-12-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organograma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='andamento',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='texto',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
