# Generated by Django 2.1.4 on 2018-12-15 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organograma', '0002_auto_20181215_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organograma.Orgao'),
        ),
    ]
