# Generated by Django 2.1.4 on 2018-12-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organograma', '0002_auto_20181214_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='funcao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='texto',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
