# Generated by Django 2.1.4 on 2018-12-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organograma', '0003_auto_20181214_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='custo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
