# Generated by Django 2.1.4 on 2018-12-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organograma', '0003_projeto_orgao'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgao',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='orgao',
            name='sigla',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='sigla',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
