# Generated by Django 2.1.4 on 2018-12-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organograma', '0004_auto_20181215_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
