# Generated by Django 2.1.4 on 2018-12-15 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organograma', '0005_projeto_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='foto',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='funcao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='local',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='responsavel',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(blank=True, default='Ativo', max_length=40, null=True),
        ),
    ]
