# Generated by Django 2.1.4 on 2018-12-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organograma', '0006_auto_20181215_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='cordenador',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='lider',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
