# Generated by Django 2.1.4 on 2018-12-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organograma', '0007_auto_20181215_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='next_release',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
