# Generated by Django 2.1.4 on 2018-12-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organograma', '0008_projeto_next_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='next_release',
            field=models.DateField(blank=True, null=True),
        ),
    ]
