# Generated by Django 2.1.4 on 2018-12-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organograma', '0009_auto_20181215_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='gitlab_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
