# Generated by Django 2.1.4 on 2018-12-16 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organograma', '0010_projeto_gitlab_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='created_at',
        ),
    ]
