# Generated by Django 2.1.4 on 2018-12-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organograma', '0011_remove_projeto_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='nome',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
